export { default as Dashboard } from './Dashboard/Dashboard';
export { default as Kanban } from './Kanban/Kanban';
export { default as Orders } from './Orders/Orders';
export { default as Customers } from './Customers/Customers';
export { default as Calendar } from './Calendar/Calendar';
// export { default as ColorPicker } from './ColorPicker';
// export { default as Area } from './Charts/Area';
// export { default as Bar } from './Charts/Bar';
// export { default as ColorMapping } from './Charts/ColorMapping';
// export { default as Financial } from './Charts/Financial';
// export { default as Line } from './Charts/Line';
// export { default as Pie } from './Charts/Pie';
// export { default as Pyramid } from './Charts/Pyramid';
// export { default as Stacked } from './Charts/Stacked';